fix(pendulum): Make PendulumDateTime work with postgres
kvesteri/sqlalchemy-utils pull request #755
Opened 2024-09-06 09:28 UTC by torotil

fixes #754

2024-09-06 11:09 UTC, kurtmckee requested changes

2024-09-06 11:09 UTC, kurtmckee commented on sqlalchemy_utils/types/enriched_datetime/pendulum_datetime.py
> +            return pendulum.DateTime.instance(value.replace(tzinfo=datetime.timezone.utc))
flake8 is unhappy. Gonna commit this suggestion to try making it happy.

```suggestion
            return pendulum.DateTime.instance(
                value.replace(tzinfo=datetime.timezone.utc)
            )
```

2024-09-06 11:16 UTC, kurtmckee approved these changes

2024-09-06 11:19 UTC, merged

2024-09-06 11:19 UTC, kurtmckee commented
Thanks for this fix, and for including a test case to demonstrate it!

2024-09-06 12:42 UTC, torotil commented
… and thanks to you for merging this so quickly!

2024-09-30 15:41 UTC, torotil commented
@kurtmckee I have now taken a more in-depth look at the code in enriched_datetime. To me it seems a bit overly complicated. I think the indirection using the EnrichedDate / EnrichedDateTime objects is not actually worth it. There is  almost no code shared between those classes. I have made a draft of removing that (and updating the the docs). Are you interested in getting a PR in that direction? (The draft can be found here: https://github.com/kvesteri/sqlalchemy-utils/compare/master...torotil:sqlalchemy-utils:refactor-enriched_datetime)

I also discovered that the arrow implementation already handles both timezone-aware and naive objects while the pendulum implementation seems to only handle naive ones (especially after the changes in this PR). I suppose this would need more test cases on the pendulum side.

2024-09-30 16:53 UTC, kurtmckee commented
PRs are welcome, but I hope that there will be others with more knowledge of the codebase that @kvesteri is able to bring on board for maintenance.