Fix arrow python type
kvesteri/sqlalchemy-utils pull request #765
Opened 2024-11-26 20:24 UTC by tim-haselhoff

Fix sqlalchemy returning datetime in python instead of arrow when using arrow

2024-11-28 21:55 UTC, benedikt-bartscher approved these changes

2024-12-30 21:28 UTC, benedikt-bartscher commented
@kvesteri foremost: thanks for maintaining sqlalchemy-utils. We really enjoyed using it so far.

Is there any way we can get this in? I would love to help if there is anything left to do

2025-01-10 11:16 UTC, torotil commented
I think that this whole part of sqlalchemy-utils needs some work (see #761) … and it seems that there is currently noone around to maintain this code properly (ie. with an opinion on its architecture).

Having said that I had luck getting a bug fix in (#754) by also providing a test case that demonstrates the issue.

2025-01-10 11:20 UTC, benedikt-bartscher commented
We could add a small test for it if required. @tim-haselhoff wdyt?

2025-07-22 16:48 UTC, kurtmckee requested changes
There appear to be several unnecessary changes here; the only thing that appears necessary is to add:

```python
        @property
        def python_type(self):
            return Arrow
```

Please add a unit test to demonstrate that this is resolving a bug.

2025-07-22 16:48 UTC, kurtmckee commented on sqlalchemy_utils/types/arrow.py
> +from arrow import Arrow
This results in an `ImportError` if arrow isn't installed; the current architecture is to allow for imports within the `sqlalchemy_utils` package but only raise an exception if a class is used but the underlying dependency isn't installed.

2026-07-08 18:37 UTC, kurtmckee commented
Closing for lack of response.

2026-07-08 18:37 UTC, closed without merging